### ISSUE TITLE
Safari open from terminal fails on macOS 10.14.2

### ISSUE THREAD

**Issue by dbuenzli** [b0-system/b0#1]
@avsm wrote:

```
$ odig browse online-doc odig
450:513: execution error: Error on line 13: Error: Can't get object. (-1728)
odig: [ERROR] show uri https://erratique.ch/software/odig/doc: safari jxa: cmd ['/usr/bin/osascript' '-l' 'JavaScript' '-' 'false' 'false' 'https://erratique.ch/software/odig/doc']: 
exited [1]
```

It appears [that activating accessibility](https://apple.stackexchange.com/questions/291574/osascript-is-not-allowed-assistive-access-1728) may fix this (but doesn't for my local setup).  Creating this issue as you may want to trap this exception and point the user to those options if they work for others.

**Comment by dbuenzli** [comment]
Humpf that's annoying. I guess you can always try with `BROWSER=open` but that's a bit more limited. Quite annoying here:
```
 odig browse --browser=safari online-doc odig 
```
works I don't know why exactly but I vaguely remember being asked for a permission at some point. Don't know exactly why this doesn't work for you.

**Comment by dbuenzli** [comment]
@avsm What did you try exactly doesn't the following work for you ? Go to 

    System Settings->Security & Privacy->Tab Privacy->Automation 

Here I personally have the following list:

![image](https://user-images.githubusercontent.com/485596/54111695-cb10ef80-43e4-11e9-8809-ebcb7fee3b0f.png)

If I unselect any option then the jxa script fails for `--browser=safari` or `--browser=chrome` however with a (-1743) error.

**Comment by avsm** [comment]
Hm I have exactly that in my setup (just safari -- i dont have chrome). I've got some other hypervisor-level things installed that might be messing with this, but it seems the wrong layer for that to affect. Will investigate

**Comment by dbuenzli** [comment]
Closing this for now. Feel free to add details if you find something.
