### ISSUE TITLE
OCaml 5 threads META change breaks handling of threads library

### ISSUE THREAD

**Issue by saagraa** [b0-system/b0#11]
The META file for the threads library was simplified for OCaml 5+ https://github.com/ocaml/ocaml/commit/d2f7460817eb9bc7ffc82efe0f8f86152d567dbf

B0 special handles threads https://github.com/b0-system/b0/blob/9acb52b5d565df274f018d72f6d724eba2cf674a/src/b00/kit/b00_ocaml.ml#L819 which is required for <=4.14.1

The result of the ocamlfind query for threads on <=4.14.1 yields:
`> ocamlfind query threads.posix -predicates "byte,native,mt,mt_posix" -format "%m:%d:%A:%(requires):%(jsoo_runtime)"
~/.opam/4.14.1/lib/threads/META:~/.opam/4.14.1/lib/ocaml/threads:threads.cma:unix:`

And on OCaml 5.0.0 (the mt and mt_posix are pointless here, but don't change the output)
`> ocamlfind query threads.posix -predicates "byte,native,mt,mt_posix" -format "%m:%d:%A:%(requires):%(jsoo_runtime)"
~/.opam/5.0.0/lib/ocaml/threads/META:~/.opam/5.0.0/lib/ocaml/threads::threads:`

Looking up `threads` instead of `threads.posix`does give us the `threads.cma`, but due to the special casing that never gets looked up.

I think as a fix it works to change it to this:
```
let lib, predicates = match Name.to_string n with
  | "ocaml.threads" | "threads" ->
    "threads", "byte,native,mt,mt_posix"
  | "threads.posix" ->
    "threads.posix", "byte,native,mt,mt_posix"
  | n -> n, "byte,native"
in
```

**Comment by dbuenzli** [comment]
Thanks. Does the problem already show up in 5.0 or only in 5.1 ?

**Comment by saagraa** [comment]
Problem is there in 5.0.0

**Comment by dbuenzli** [comment]
Thanks for the report. I pushed a fix. 

> I think as a fix it works to change it to this:

This would have broken the idea that you can always use any of `ocaml.threads`, `threads` and `threads.posix`. As you can see in 4443535ca9081b8d403e7ccbc174677d845a9873 I simply ended up conditionalizing the lookup on the ocaml version.
