### ISSUE TITLE
B0_ocaml: linking c libraries fails in some configurations

### ISSUE THREAD

**Issue by saagraa** [b0-system/b0#12]
Apologies in advance, I'm not certain if this a problem with B0 or something else.

In this repo (https://github.com/saagraa/ocaml_linking_example) I have a few makefiles and a B0.ml file:
- `Makefile.b0` is in attempt to copy what B0 does
- `Makefile` and `Makefile.2` swap the order of the `-cclib` parameters. They exclusively use `-cclib`, whereas the b0 one uses `-ccopt`
- Swapping the order of `-cclib` and `-ccopt` didn't impact the results in `Makefile.b0`.

I've got two systems:
System A: 
- Ubuntu
- Linux 5.4
- gcc 9.4
- ld 2.34
- Ocaml 4.14.1 (`ocamlopt -config-var native_c_libraries => -lm -ldl`)

System B
- Void Linux
- Linux 4.4
- gcc 12.2
- ld 2.39
- Ocaml 4.14.1 (`ocaml -config-var native_c_libraries => -lm`)

On System A (older gcc/ld):
- `make` works and links `main`
- `make -f Makefile.2` results in an ld error
- `make -f Makefile.b0` results in an ld error
- `b0` results in an ld error

On System B (newer gcc/ld):
- `make` works and links `main`
- `make -f Makefile.2`  works and links `main`
- `make -f Makefile.b0`  works and links `main`
- `b0` works and links `main`

I'm guessing this is caused by some change from gcc 9.4 -> 12.2 and ld 2.34 -> 2.39. Nothing in the [ld news](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=ld/NEWS;hb=refs/heads/binutils-2_40-branch) file stands out to me though.

**Comment by dbuenzli** [comment]
`c_requires` was definitively broken, it was using `-ccopt` instead of `-cclib`. That is in `.cmxa` files instead for example of:

```
Extra C object files: -lbytesrw_zstd_stubs -lzstd 
Extra C options:
```
we had:
```
Extra C object files: -lbytesrw_zstd_stubs
Extra C options: -lzstd 
```

However that worked for some reasons on some platforms (e.g. `macos`), same for the second commit.
