### ISSUE TITLE
ocamlfind invocation ignores OCAMLPATH variable

### ISSUE THREAD

**Issue by saagraa** [b0-system/b0#13]
`ocamlfind` gets called with an empty environment (or atleast `b0 file log --id 4 -l` show nothing in env). I guess this doesn't matter when the toolchain and packages are all managed by opam, and it gets all its values from findlib.conf.

My local fix was to add `~vars:["OCAMLPATH"]` to the tool lookup. I'm not sure which or if all of the [env vars](http://projects.camlcity.org/projects/dl/findlib-1.9.6/doc/ref-html/r865.html#FINDLIB.CONF) ocamlfind uses should be added there.

Problem is present at the latest commit and latest tag (v0.0.5)

**Comment by dbuenzli** [comment]
Thanks for the report and reference I added all of them (in a private branch for technical reasons, will push master in a few days).
