### ISSUE TITLE
`b0` freezes when we query a library which does not have an archive

### ISSUE THREAD

**Issue by dinosaure** [b0-system/b0#15]
Actually, it seems that if our project depends on `compiler-libs‧common`, `b0` tries to solve dependencies and ask the archive of `compiler-libs` which does not exist. Not sure why `b0` freezes  but the situation is reproducible with this `B0.ml` file and an empty `foo‧ml` file:
```ocaml
open B0_kit.V000

let foo = B0_ocaml‧libname "foo"
let compiler_libs_common = B0_ocaml‧libname "compiler-libs.common"

let foo_library =
  let srcs = Fpath.[ `File ~/"foo‧ml" ] in
  let requires = [ compiler_libs_common ] in
  B0_ocaml‧lib foo ~srcs ~requires

let default =
  B0_pack‧make "default" ~locked:true @@
  B0_unit‧list ()
```

Then, I tried to launch `b0 -u foo -- .ocaml‧ocaml` to launch the REPL but it does not work.

**Comment by dbuenzli** [comment]
Wrong diagnostic, but real bug. Thanks.
