### ISSUE TITLE
Building one Unit with another

### ISSUE THREAD

**Issue by saagraa** [b0-system/b0#6]
I'm trying to use the one unit to build another. The code below works sometimes. When it doesn't, I get error code 127, so I guess I `Os.Cmd.run` is trying to run before `prog`'s exe_file is generated. Am I missing something in declaring the dependencies/requirements?

```ocaml
open B0_kit.V000 
open B00_std
open B00_std.Fut.Syntax
   
let execute prog outfile =
  match B0_unit.get_meta B0_meta.exe_file prog with
  | Error e -> Log.err (fun m -> m "Begin: %s" e); Fut.return B00_cli.Exit.some_error
  | Ok exe_file ->
     let* exe_file = exe_file in
     let cmd = Cmd.path exe_file in
     let out = Os.Cmd.out_file ~force:true ~make_path:true outfile in
     begin match
       Os.Cmd.run ~stdout:out cmd with
     | Ok () -> Fut.return (Os.Exit.Code 0)
     | Error e -> Log.err (fun m -> m "End: %s" e); Fut.return B00_cli.Exit.some_error
     end
     
let generator ?doc ?meta name (prog : B0_unit.t) =
  let proc = fun b ->
    B0_build.require b prog;
    let u = B0_build.current b in
    let bd = B0_build.build_dir b u in
    let outfile = Fpath.(bd / name) in
    Log.warn  (fun m -> m "Outfile: %s" (Fpath.to_string outfile));
    let* ret_code = execute prog outfile in
    if Os.Exit.get_code ret_code = 0 then
      Fut.return ()
    else
      Fut.return ()
  in
  B0_unit.v ?doc ?meta name proc
```

**Comment by dbuenzli** [comment]
Please don't use `b0` for now. 

But basically the `Os.Cmd` API should not be used in build procedures. You have to spawn your tool with the [memoizer](https://erratique.ch/software/b0/doc/B00/Memo/index.html#spawn) which takes care of ensure all the files it reads (that includes the program itself) are ready (i.e. exists or are built) to proceed.

**Comment by saagraa** [comment]
> Please don't use `b0` for now.

I've noticed all the "not for production" and "subject to change" comments in the documentation; I found the rationale page compelling and wanted to explore a bit. I'll keep all my critical projects in other build systems for now.
 
> But basically the `Os.Cmd` API should not be used in build procedures. You have to spawn your tool with the [memoizer](https://erratique.ch/software/b0/doc/B00/Memo/index.html#spawn) which takes care of ensure all the files it reads (that includes the program itself) are ready (i.e. exists or are built) to proceed.

Ahh this makes sense. Thank you, I missed that part of the documentation.

**Comment by saagraa** [comment]
Using Memo and it works as expected. 
```ocaml
open B0_kit.V000 
open B00_std
open B00_std.Fut.Syntax
   
let proc name prog b =
  B0_build.require b prog;
  let m = B0_build.memo b in
  let u = B0_build.current b in
  let bd = B0_build.build_dir b u in
  let outfile = Fpath.(bd / name) in
  match B0_unit.get_meta B0_meta.exe_file prog with
  | Error e -> B00.Memo.fail m "not an executable: %s" e
  | Ok exe_file ->
     let* exe_file = exe_file in
     let tool = B00.Tool.v exe_file in
     let cmd = B00.Memo.tool m tool Cmd.empty in
     B00.Memo.spawn m ~writes:[outfile] ~stdout:(`File outfile) cmd |> Fut.return
     
let gen_with ?doc ?meta ~prog name =
  B0_unit.v ?doc ?meta name (proc name prog)
```

**Comment by dbuenzli** [comment]
I hope we can eventually streamline a bit all that :-) (or not since we have abstraction) but you got the idea.

I removed quite a bit of the stuff (e.g. configuration, variants) from `b0` to try get a clearer picture but I'm using it myself for dev (but not for release builds). If you really want to suffer you can peek into the `B0.ml` files [here](https://github.com/dbuenzli/brr/blob/master/B0.ml) and [there](https://github.com/b0-system/b0/blob/master/B0.ml) but the most interesting ones I have are for private projects.
