### ISSUE TITLE
Ocaml build not waiting for lib*_stubs* to be complete

### ISSUE THREAD

**Issue by saagraa** [b0-system/b0#9]
When building a library with c stubs, the first build attempt errors with:
```
/usr/sbin/ld: cannot find -lmylib_stubs
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

I have fixed this locally by adding:
```ocaml
let reads = if has_cstubs then
  let cstubs = Fpath.(odir / cstubs_clib oname lib_ext) in
      cstubs :: reads
  else
    reads
in
Memo.spawn ...
```
to B00_ocaml.Archive.native and something similar to B00_ocaml.Archive.byte.

**Comment by saagraa** [comment]
Some more digging. I think my fix was misplaced (though it does fix the error). The problem occurs in this sort of situation:
```ocaml
let lib = B0_ocaml.libname "lib"
let lib_unit = B0_ocaml.lib ~srcs:[`Dir some_dir_with_c_stubs] lib

let  test = B0_ocaml.exe ~requires:[lib] ~srcs:[`Dir tests_dir] "test"
```
And then invoking `b0` from a clean state (e.g. after `rm -r _b0`). `b0 build -u lib` runs fine

**Comment by dbuenzli** [comment]
Sorry but I don't have the time to look into this. There are some race conditions in the system (most notably with `ocamlfind` lookup) and I'm not sure where they stem from. So this may be related to that.

**Comment by saagraa** [comment]
> Sorry but I don't have the time to look into this. There are some race conditions in the system (most notably with `ocamlfind` lookup) and I'm not sure where they stem from. So this may be related to that.

No worries. 

I think I found the cause: 
https://github.com/b0-system/b0/blob/6e538ebacf7b2a7c5943a9b38bffbd33fdceb6c0/src/kit/b0_ocaml.ml#L116

**Comment by saagraa** [comment]
I was going to have a go at solving this, but I pretty much immediately came to a choice and I'm not sure which approach to use:

1. Use an approach similar to how modsrcs is done currently. Create a future meta, set it in `lib_proc`, read it from meta in `Lib.of_unit`. Would work, relatively simple, however in defining the meta key for `modsrcs` there is `(* FIXME don't do that. *)` so I assume this isn't the approach you'd like.

2. Solve it in `B0_ocaml.Link` where there is the comment:
    ```
    (* FIXME Add cstubs archives of cm[x]a to [reads] ? Do we need it ?
       that would entail an ocamlobjinfo + C library lookup *)
    ```
    But I think, in general, we don't need it. It's probably more correct to have it, but its pretty safe to assume that any library we are linking to that is not built in the project (e.g. from system package manager or opam) would have all the files present, and that the libraries don't change on their own without any of the other files being changed.

3. What about just having a `lib` meta key and creating a `B0_ocaml.Lib.t` directly in the `lib_proc`. This would also get rid of the `modsrcs` meta key.

**Comment by dbuenzli** [comment]
> 3\. This would also get rid of the `modsrcs` meta key.

For now I kept that around. But the whole logic will need a good rewrite at some point. Thanks for your proposition which, except on details, I mostly followed.
